### ISSUE TITLE
Allow group specification for authimap users

### ISSUE THREAD

**Issue by richardneish** [cosmocode/dokuwiki-plugin-authimap#2]
I would like all users, including admins, to authenticate through authimap, but there is no way at the moment to add an authimap user to the `admins` group.

My initial thoughts are to add a config parameter something like 

```
$conf['plugin']['authimap']['groups']['myadminuser'] = 'admin,othergroup';
```

and then modify `getUserData($user)` to return the groups for the user if they exist, or fallback to `$conf['defaultgroup']` if no groups are specified for the user.  I guess that we should also set `$this->cando['getGroups'] = true;` and implement `getGroups($user)`.

**Comment by splitbrain** [comment]
You can specify users directly in the superuser config setting - no need for an admin group. otherwise see my comment in #1

**Comment by richardneish** [comment]
Ah, ok, that works.  Thanks.
